---
  flow-definitions:
    - name: pypi
      queue: pypi_flow
      edges:
        - from:
          to: PyPIListingTask
        - from: PyPIListingTask
          to: pypi_project
          foreach:
            function: iter_pypi_projects
            import: thoth.worker.foreach
            propagate_result: true

    - name: pypi_project
      queue: pypi_project_flow
      nowait:
        - ProjectInfoTask
      edges:
        - from:
          to: ProjectInfoTask

    - name: readme_file
      queue: readme_file_flow
      edges:
        - from:
          to: RetrieveProjectReadmeTask

    - name: project_readme_files
      queue: project_readme_files_flow
      edges:
        - from:
          to: readme_file
          foreach:
            function: iter_pypi_projects_ceph
            import: thoth.worker.foreach
            propagate_result: true
