apiVersion: v1
kind: Template
labels:
  template: worker-deploymentconfig
  selinon: 1.0.0
metadata:
  name: worker-deploymentconfig
  annotations:
    description: Selinon API
    openshift.io/display-name: 'Selinon: API'
    version: 1.0.0
    tags: poc,selinon,worker
    template.openshift.io/documentation-url: https://github.com/selinon/
    template.openshift.io/long-description: Selinon worker deployment configuration template.
    template.openshift.io/provider-display-name: Fridolin Pokorny

objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: worker
      app: selinon
      component: worker
    name: ${WORKER_NAME}
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          service: worker
      spec:
        containers:
        - env:
          - name: THOTH_CEPH_BUCKET
            value: ${THOTH_CEPH_BUCKET}
          - name: THOTH_CEPH_BUCKET_PREFIX
            value: ${THOTH_CEPH_BUCKET_PREFIX}
          - name: THOTH_CEPH_KEY_ID
            value: ${THOTH_CEPH_KEY_ID}
          - name: THOTH_CEPH_SECRET_KEY
            value: ${THOTH_CEPH_SECRET_KEY}
          - name: THOTH_S3_ENDPOINT_URL
            value: ${THOTH_S3_ENDPOINT_URL}
          - name: SELINON_DISPATCHER
            value: ${SELINON_DISPATCHER}
          - name: THOTH_LOG_WORKER
            value: INFO
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: thoth
                key: sentry-dsn
          - name: BROKER_URL
            valueFrom:
              configMapKeyRef:
                name: selinon
                key: broker-url
          - name: RESULT_BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: selinon
                key: result-backend-url
          name: worker
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          # TODO: readinessProbe:
          # TODO: livenessProbe:
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - worker
        from:
          kind: ImageStreamTag
          name: 'worker:latest'

parameters:
- description: Name of worker.
  displayName: Worker name.
  required: true
  name: WORKER_NAME
  value: 'worker'

- description: The given worker is Selinon dispatcher worker.
  displayName: Selinon dispatcher worker.
  required: true
  name: SELINON_DISPATCHER

- description: Ceph bucket to be used.
  displayName: Ceph bucket name
  required: true
  name: THOTH_CEPH_BUCKET

- description: Ceph bucket prefix.
  displayName: Ceph bucket prefix
  required: true
  name: THOTH_CEPH_BUCKET_PREFIX

- description: Ceph key id to be used.
  displayName: Ceph key id
  required: true
  name: THOTH_CEPH_KEY_ID

- description: Secret key to be used to Ceph.
  displayName: Ceph secret key
  required: true
  name: THOTH_CEPH_SECRET_KEY

- description: S3 endpoint used for communicating with Ceph.
  displayName: S3 endpoint
  required: true
  name: THOTH_S3_ENDPOINT_URL
