apiVersion: v1
kind: Template
metadata:
  name: worker-imagestream
  labels:
    app: selinon
  annotations:
    description: Selinon worker image stream
    openshift.io/display-name: 'Selinon: worker'
    version: 1.0.0
    tags: poc,selinon,worker
    template.openshift.io/documentation-url: https://github.com/selinon
    template.openshift.io/long-description: Selinon API worker stream definition
    template.openshift.io/provider-display-name: Fridolin Pokorny

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: selinon
    name: worker
  spec:
    name: latest
